name: Auto Docker build

on:
  push:
    branches:
      - "*"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: checkout and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Checkout platform
        uses: actions/checkout@v6
        with:
          repository: scutrobotlab/saleor-platform
          path: platform

      - name: Start mock platform
        run: |
          cd platform
          docker compose up -d api

          # wait for the API to be ready
          until curl -s http://localhost:8000/graphql/; do
            echo "Waiting for API to be ready..."
            sleep 5
          done

          docker compose run --rm api python3 manage.py migrate
          docker compose run --rm api python3 manage.py populatedb

      - uses: docker/setup-buildx-action@v4
        with:
          driver: docker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          network: host
          build-args: |
            NEXT_PUBLIC_SALEOR_API_URL=http://localhost:8000/graphql/
            NEXT_PUBLIC_DEFAULT_CHANNEL=default-channel
            NEXT_PUBLIC_STOREFRONT_URL=https://store.scutbot.cn
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
